### ISSUE TITLE
[Bug] Position of callout label on shop not running

### ISSUE THREAD

**Issue by HugFes** [Setono/SyliusCalloutPlugin#11]
Positioning based on [Semantic ui](https://semantic-ui.com/elements/label.html#attached) not running
**Cause** : The classes order. The position  classes (top, bottom, left right) must be placed before the `attached` class.

**Solution**: rewrite `Setono\SyliusCalloutPlugin\Callout\SemanticUiCssClassBuilder` to have correct order

**Comment by loevgaard** [comment]
I believe that people don't use Semantic UI anymore and hence the Semantic UI class builder is just for the test application. It's better to define your own class builder according to your layout
