### ISSUE TITLE
Multiple callouts at the same position renders as one (only last visible)

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusCalloutPlugin#4]
Postponed. Require rework and major release (e.g. `0.1` > `0.2`).

**Comment by loevgaard** [comment]
In the upcoming v0.5 only one callout is returned per element and position. See https://github.com/Setono/SyliusCalloutPlugin/blob/0.5.x/src/Twig/CalloutRuntime.php#L30
